spring:
  application:
    name: final
  datasource:
    url: jdbc:postgresql://dpg-d1alq8je5dus73eo52cg-a.virginia-postgres.render.com:5432/servicios_s7o5
    username: usuariofinal
    password: VM1UardO0TLDVfwfqklOogHPgwOT0Wa1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 10000

logging:
  level:
    org.springframework.security: DEBUG
